package jp.co.shekeen.WidgetHolder;

public class StatusIcons {
	
	public static final int BATTERY_LEVEL_ICONS[] = {
		R.drawable.percent_0, R.drawable.percent_1, R.drawable.percent_2, R.drawable.percent_3, R.drawable.percent_4, 
		R.drawable.percent_5, R.drawable.percent_6, R.drawable.percent_7, R.drawable.percent_8, R.drawable.percent_9, 
		R.drawable.percent_10, R.drawable.percent_11, R.drawable.percent_12, R.drawable.percent_13, R.drawable.percent_14, 
		R.drawable.percent_15, R.drawable.percent_16, R.drawable.percent_17, R.drawable.percent_18, R.drawable.percent_19, 
		R.drawable.percent_20, R.drawable.percent_21, R.drawable.percent_22, R.drawable.percent_23, R.drawable.percent_24, 
		R.drawable.percent_25, R.drawable.percent_26, R.drawable.percent_27, R.drawable.percent_28, R.drawable.percent_29, 
		R.drawable.percent_30, R.drawable.percent_31, R.drawable.percent_32, R.drawable.percent_33, R.drawable.percent_34, 
		R.drawable.percent_35, R.drawable.percent_36, R.drawable.percent_37, R.drawable.percent_38, R.drawable.percent_39, 
		R.drawable.percent_40, R.drawable.percent_41, R.drawable.percent_42, R.drawable.percent_43, R.drawable.percent_44, 
		R.drawable.percent_45, R.drawable.percent_46, R.drawable.percent_47, R.drawable.percent_48, R.drawable.percent_49, 
		R.drawable.percent_50, R.drawable.percent_51, R.drawable.percent_52, R.drawable.percent_53, R.drawable.percent_54, 
		R.drawable.percent_55, R.drawable.percent_56, R.drawable.percent_57, R.drawable.percent_58, R.drawable.percent_59, 
		R.drawable.percent_60, R.drawable.percent_61, R.drawable.percent_62, R.drawable.percent_63, R.drawable.percent_64, 
		R.drawable.percent_65, R.drawable.percent_66, R.drawable.percent_67, R.drawable.percent_68, R.drawable.percent_69, 
		R.drawable.percent_70, R.drawable.percent_71, R.drawable.percent_72, R.drawable.percent_73, R.drawable.percent_74, 
		R.drawable.percent_75, R.drawable.percent_76, R.drawable.percent_77, R.drawable.percent_78, R.drawable.percent_79, 
		R.drawable.percent_80, R.drawable.percent_81, R.drawable.percent_82, R.drawable.percent_83, R.drawable.percent_84, 
		R.drawable.percent_85, R.drawable.percent_86, R.drawable.percent_87, R.drawable.percent_88, R.drawable.percent_89, 
		R.drawable.percent_90, R.drawable.percent_91, R.drawable.percent_92, R.drawable.percent_93, R.drawable.percent_94, 
		R.drawable.percent_95, R.drawable.percent_96, R.drawable.percent_97, R.drawable.percent_98, R.drawable.percent_99, 
		R.drawable.percent_100
	};
	
	public static final int BATTERY_LEVEL_BAR_ICONS[] = {
		R.drawable.percent_bar_0, R.drawable.percent_bar_1, R.drawable.percent_bar_2, R.drawable.percent_bar_3, R.drawable.percent_bar_4, 
		R.drawable.percent_bar_5, R.drawable.percent_bar_6, R.drawable.percent_bar_7, R.drawable.percent_bar_8, R.drawable.percent_bar_9, 
		R.drawable.percent_bar_10, R.drawable.percent_bar_11, R.drawable.percent_bar_12, R.drawable.percent_bar_13, R.drawable.percent_bar_14, 
		R.drawable.percent_bar_15, R.drawable.percent_bar_16, R.drawable.percent_bar_17, R.drawable.percent_bar_18, R.drawable.percent_bar_19, 
		R.drawable.percent_bar_20, R.drawable.percent_bar_21, R.drawable.percent_bar_22, R.drawable.percent_bar_23, R.drawable.percent_bar_24, 
		R.drawable.percent_bar_25, R.drawable.percent_bar_26, R.drawable.percent_bar_27, R.drawable.percent_bar_28, R.drawable.percent_bar_29, 
		R.drawable.percent_bar_30, R.drawable.percent_bar_31, R.drawable.percent_bar_32, R.drawable.percent_bar_33, R.drawable.percent_bar_34, 
		R.drawable.percent_bar_35, R.drawable.percent_bar_36, R.drawable.percent_bar_37, R.drawable.percent_bar_38, R.drawable.percent_bar_39, 
		R.drawable.percent_bar_40, R.drawable.percent_bar_41, R.drawable.percent_bar_42, R.drawable.percent_bar_43, R.drawable.percent_bar_44, 
		R.drawable.percent_bar_45, R.drawable.percent_bar_46, R.drawable.percent_bar_47, R.drawable.percent_bar_48, R.drawable.percent_bar_49, 
		R.drawable.percent_bar_50, R.drawable.percent_bar_51, R.drawable.percent_bar_52, R.drawable.percent_bar_53, R.drawable.percent_bar_54, 
		R.drawable.percent_bar_55, R.drawable.percent_bar_56, R.drawable.percent_bar_57, R.drawable.percent_bar_58, R.drawable.percent_bar_59, 
		R.drawable.percent_bar_60, R.drawable.percent_bar_61, R.drawable.percent_bar_62, R.drawable.percent_bar_63, R.drawable.percent_bar_64, 
		R.drawable.percent_bar_65, R.drawable.percent_bar_66, R.drawable.percent_bar_67, R.drawable.percent_bar_68, R.drawable.percent_bar_69, 
		R.drawable.percent_bar_70, R.drawable.percent_bar_71, R.drawable.percent_bar_72, R.drawable.percent_bar_73, R.drawable.percent_bar_74, 
		R.drawable.percent_bar_75, R.drawable.percent_bar_76, R.drawable.percent_bar_77, R.drawable.percent_bar_78, R.drawable.percent_bar_79, 
		R.drawable.percent_bar_80, R.drawable.percent_bar_81, R.drawable.percent_bar_82, R.drawable.percent_bar_83, R.drawable.percent_bar_84, 
		R.drawable.percent_bar_85, R.drawable.percent_bar_86, R.drawable.percent_bar_87, R.drawable.percent_bar_88, R.drawable.percent_bar_89, 
		R.drawable.percent_bar_90, R.drawable.percent_bar_91, R.drawable.percent_bar_92, R.drawable.percent_bar_93, R.drawable.percent_bar_94, 
		R.drawable.percent_bar_95, R.drawable.percent_bar_96, R.drawable.percent_bar_97, R.drawable.percent_bar_98, R.drawable.percent_bar_99, 
		R.drawable.percent_bar_100
	};
	
	public static final int BATTERY_TEMP_ICONS[] = {
		R.drawable.degree_0, R.drawable.degree_1, R.drawable.degree_2, R.drawable.degree_3, R.drawable.degree_4, 
		R.drawable.degree_5, R.drawable.degree_6, R.drawable.degree_7, R.drawable.degree_8, R.drawable.degree_9, 
		R.drawable.degree_10, R.drawable.degree_11, R.drawable.degree_12, R.drawable.degree_13, R.drawable.degree_14, 
		R.drawable.degree_15, R.drawable.degree_16, R.drawable.degree_17, R.drawable.degree_18, R.drawable.degree_19, 
		R.drawable.degree_20, R.drawable.degree_21, R.drawable.degree_22, R.drawable.degree_23, R.drawable.degree_24, 
		R.drawable.degree_25, R.drawable.degree_26, R.drawable.degree_27, R.drawable.degree_28, R.drawable.degree_29, 
		R.drawable.degree_30, R.drawable.degree_31, R.drawable.degree_32, R.drawable.degree_33, R.drawable.degree_34, 
		R.drawable.degree_35, R.drawable.degree_36, R.drawable.degree_37, R.drawable.degree_38, R.drawable.degree_39, 
		R.drawable.degree_40, R.drawable.degree_41, R.drawable.degree_42, R.drawable.degree_43, R.drawable.degree_44, 
		R.drawable.degree_45, R.drawable.degree_46, R.drawable.degree_47, R.drawable.degree_48, R.drawable.degree_49, 
		R.drawable.degree_50, R.drawable.degree_51, R.drawable.degree_52, R.drawable.degree_53, R.drawable.degree_54, 
		R.drawable.degree_55, R.drawable.degree_56, R.drawable.degree_57, R.drawable.degree_58, R.drawable.degree_59, 
		R.drawable.degree_60, R.drawable.degree_61, R.drawable.degree_62, R.drawable.degree_63, R.drawable.degree_64, 
		R.drawable.degree_65, R.drawable.degree_66, R.drawable.degree_67, R.drawable.degree_68, R.drawable.degree_69, 
		R.drawable.degree_70, R.drawable.degree_71, R.drawable.degree_72, R.drawable.degree_73, R.drawable.degree_74, 
		R.drawable.degree_75, R.drawable.degree_76, R.drawable.degree_77, R.drawable.degree_78, R.drawable.degree_79, 
		R.drawable.degree_80, R.drawable.degree_81, R.drawable.degree_82, R.drawable.degree_83, R.drawable.degree_84, 
		R.drawable.degree_85, R.drawable.degree_86, R.drawable.degree_87, R.drawable.degree_88, R.drawable.degree_89, 
		R.drawable.degree_90, R.drawable.degree_91, R.drawable.degree_92, R.drawable.degree_93, R.drawable.degree_94, 
		R.drawable.degree_95, R.drawable.degree_96, R.drawable.degree_97, R.drawable.degree_98, R.drawable.degree_99, 
	};
	
	public static final int BATTERY_TEMP_ICONS_FAH[] = {
		R.drawable.fdegree_0, R.drawable.fdegree_1, R.drawable.fdegree_2, R.drawable.fdegree_3, R.drawable.fdegree_4, 
		R.drawable.fdegree_5, R.drawable.fdegree_6, R.drawable.fdegree_7, R.drawable.fdegree_8, R.drawable.fdegree_9, 
		R.drawable.fdegree_10, R.drawable.fdegree_11, R.drawable.fdegree_12, R.drawable.fdegree_13, R.drawable.fdegree_14, 
		R.drawable.fdegree_15, R.drawable.fdegree_16, R.drawable.fdegree_17, R.drawable.fdegree_18, R.drawable.fdegree_19, 
		R.drawable.fdegree_20, R.drawable.fdegree_21, R.drawable.fdegree_22, R.drawable.fdegree_23, R.drawable.fdegree_24, 
		R.drawable.fdegree_25, R.drawable.fdegree_26, R.drawable.fdegree_27, R.drawable.fdegree_28, R.drawable.fdegree_29, 
		R.drawable.fdegree_30, R.drawable.fdegree_31, R.drawable.fdegree_32, R.drawable.fdegree_33, R.drawable.fdegree_34, 
		R.drawable.fdegree_35, R.drawable.fdegree_36, R.drawable.fdegree_37, R.drawable.fdegree_38, R.drawable.fdegree_39, 
		R.drawable.fdegree_40, R.drawable.fdegree_41, R.drawable.fdegree_42, R.drawable.fdegree_43, R.drawable.fdegree_44, 
		R.drawable.fdegree_45, R.drawable.fdegree_46, R.drawable.fdegree_47, R.drawable.fdegree_48, R.drawable.fdegree_49, 
		R.drawable.fdegree_50, R.drawable.fdegree_51, R.drawable.fdegree_52, R.drawable.fdegree_53, R.drawable.fdegree_54, 
		R.drawable.fdegree_55, R.drawable.fdegree_56, R.drawable.fdegree_57, R.drawable.fdegree_58, R.drawable.fdegree_59, 
		R.drawable.fdegree_60, R.drawable.fdegree_61, R.drawable.fdegree_62, R.drawable.fdegree_63, R.drawable.fdegree_64, 
		R.drawable.fdegree_65, R.drawable.fdegree_66, R.drawable.fdegree_67, R.drawable.fdegree_68, R.drawable.fdegree_69, 
		R.drawable.fdegree_70, R.drawable.fdegree_71, R.drawable.fdegree_72, R.drawable.fdegree_73, R.drawable.fdegree_74, 
		R.drawable.fdegree_75, R.drawable.fdegree_76, R.drawable.fdegree_77, R.drawable.fdegree_78, R.drawable.fdegree_79, 
		R.drawable.fdegree_80, R.drawable.fdegree_81, R.drawable.fdegree_82, R.drawable.fdegree_83, R.drawable.fdegree_84, 
		R.drawable.fdegree_85, R.drawable.fdegree_86, R.drawable.fdegree_87, R.drawable.fdegree_88, R.drawable.fdegree_89, 
		R.drawable.fdegree_90, R.drawable.fdegree_91, R.drawable.fdegree_92, R.drawable.fdegree_93, R.drawable.fdegree_94, 
		R.drawable.fdegree_95, R.drawable.fdegree_96, R.drawable.fdegree_97, R.drawable.fdegree_98, R.drawable.fdegree_99, 
		R.drawable.fdegree_100, R.drawable.fdegree_101, R.drawable.fdegree_102, R.drawable.fdegree_103, R.drawable.fdegree_104, 
		R.drawable.fdegree_105, R.drawable.fdegree_106, R.drawable.fdegree_107, R.drawable.fdegree_108, R.drawable.fdegree_109, 
		R.drawable.fdegree_110, R.drawable.fdegree_111, R.drawable.fdegree_112, R.drawable.fdegree_113, R.drawable.fdegree_114, 
		R.drawable.fdegree_115, R.drawable.fdegree_116, R.drawable.fdegree_117, R.drawable.fdegree_118, R.drawable.fdegree_119, 
		R.drawable.fdegree_120, R.drawable.fdegree_121, R.drawable.fdegree_122, R.drawable.fdegree_123, R.drawable.fdegree_124, 
		R.drawable.fdegree_125, R.drawable.fdegree_126, R.drawable.fdegree_127, R.drawable.fdegree_128, R.drawable.fdegree_129, 
		R.drawable.fdegree_130, R.drawable.fdegree_131, R.drawable.fdegree_132, R.drawable.fdegree_133, R.drawable.fdegree_134, 
		R.drawable.fdegree_135, R.drawable.fdegree_136, R.drawable.fdegree_137, R.drawable.fdegree_138, R.drawable.fdegree_139, 
		R.drawable.fdegree_140, R.drawable.fdegree_141, R.drawable.fdegree_142, R.drawable.fdegree_143, R.drawable.fdegree_144, 
		R.drawable.fdegree_145, R.drawable.fdegree_146, R.drawable.fdegree_147, R.drawable.fdegree_148, R.drawable.fdegree_149, 
		R.drawable.fdegree_150, R.drawable.fdegree_151, R.drawable.fdegree_152, R.drawable.fdegree_153, R.drawable.fdegree_154, 
		R.drawable.fdegree_155, R.drawable.fdegree_156, R.drawable.fdegree_157, R.drawable.fdegree_158, R.drawable.fdegree_159, 
		R.drawable.fdegree_160, R.drawable.fdegree_161, R.drawable.fdegree_162, R.drawable.fdegree_163, R.drawable.fdegree_164, 
		R.drawable.fdegree_165, R.drawable.fdegree_166, R.drawable.fdegree_167, R.drawable.fdegree_168, R.drawable.fdegree_169, 
		R.drawable.fdegree_170, R.drawable.fdegree_171, R.drawable.fdegree_172, R.drawable.fdegree_173, R.drawable.fdegree_174, 
		R.drawable.fdegree_175, R.drawable.fdegree_176, R.drawable.fdegree_177, R.drawable.fdegree_178, R.drawable.fdegree_179, 
		R.drawable.fdegree_180, R.drawable.fdegree_181, R.drawable.fdegree_182, R.drawable.fdegree_183, R.drawable.fdegree_184, 
		R.drawable.fdegree_185, R.drawable.fdegree_186, R.drawable.fdegree_187, R.drawable.fdegree_188, R.drawable.fdegree_189, 
		R.drawable.fdegree_190, R.drawable.fdegree_191, R.drawable.fdegree_192, R.drawable.fdegree_193, R.drawable.fdegree_194, 
		R.drawable.fdegree_195, R.drawable.fdegree_196, R.drawable.fdegree_197, R.drawable.fdegree_198, R.drawable.fdegree_199, 
	};
	
	public static int getFarTemp(int temp){
		return (temp * 9 / 5) + 32;
	}
}
